# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0796fde8c1fffb38ecdf8a93ae9daca6f844c1d169e47f02da4a8b3c24ae796e67d26ea7f0ff2f3b5333b83e4383fbcae685d4571a7a27c7771a2e525210b05

test:
  secret_key_base: a361ccafdc7684d5e497f19452b336bd78913858c098af9e9e6e5929aea4c67b45ac59b94df7db2475c50ab21849004c79ce9ccecb996394d17ce620ceae38b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
